name: CI

on:
  push:
  pull_request:

jobs:
  run-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run JavaScript files
        run: |
          node nothing.js
          node something.js